#
# IMPORTANT.  OS X support is so experimental that you have to specifically
# request to have it enabled, on a per-repository basis.  See
# http://docs.travis-ci.com/user/multi-os/#Manual-intervention-required
#
# This file will still work, without OS X enabled, it just won't run those
# tests.
#
language: python

os:
    - linux
    # - osx

# xenial = Ubuntu 16.04
# bionic = Ubuntu 18.04
dist: xenial
# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
python:
    # - 3.5
    - 3.6
    - 3.7
    - 3.8
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - MAIN_CMD='python -m unittest'
    matrix:
        # - SETUP_CMD='egg_info'
        # - SETUP_CMD='bdist_egg'
        - SETUP_CMD='discover -t py -v desiutil.test'

matrix:
    # Don't wait for allowed failures.
    fast_finish: true

    # OS X support is still experimental, so don't penalize failures.
    allow_failures:
        - os: osx
        - os: linux
          python: 3.6
          env: MAIN_CMD='pycodestyle' SETUP_CMD='--count py/desiutil'

    include:
        # Check for sphinx doc build warnings - we do this first because it
        # runs for a long time
        - os: linux
          python: 3.6
          env: MAIN_CMD='sphinx-build' SETUP_CMD='-W --keep-going -b html doc doc/_build/html'

        # Coverage test, pass the results to coveralls.
        - os: linux
          python: 3.6
          env: MAIN_CMD='coverage run -m unittest'

        - os: linux
          python: 3.6
          env: ASTROPY_VERSION='>=4.0'

        - os: linux
          python: 3.6
          env: ASTROPY_VERSION='<4.0'

        # Experimental OS X test.
        # As of March 2017, Python builds on OS X are not available.
        # See https://docs.travis-ci.com/user/languages/python/
        # - os: osx
        #   python: 3.5
        #   env: SETUP_CMD='test'

        # PEP 8 compliance.
        - os: linux
          python: 3.6
          env: MAIN_CMD='pycodestyle' SETUP_CMD='--count py/desiutil'

# before_install:
#     - curl ipinfo.io
#     - python -c 'import setuptools; print(setuptools.__version__)'

install:
    - if [[ "${MAIN_CMD}" == pycodestyle ]]; then pip install pycodestyle; fi
    - if [[ "${MAIN_CMD}" == sphinx-build* ]]; then pip install Sphinx; fi
    - if [[ "${MAIN_CMD}" == coverage* ]]; then pip install coverage coveralls; fi
    - if [[ "${MAIN_CMD}" == python* || "${MAIN_CMD}" == coverage* ]]; then pip install -r requirements.txt; fi
    - if [[ -n "${ASTROPY_VERSION}" ]]; then pip install -U "astropy${ASTROPY_VERSION}"; fi

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ "${MAIN_CMD}" == coverage* ]]; then coveralls; fi
